@startuml
rectangle "Пациент" as Client #LightGray
rectangle "Доктор" as Doctor #LightGray

rectangle "1. Приём данных пациента" as P1 #LightCyan
rectangle "2. Просмотр журнала приёма" as P2 #LightCyan
rectangle "3. Просмотр карточки пациента" as P3 #LightCyan
rectangle "4. Просмотр результатов анализов" as P4 #LightCyan
rectangle "5. Запись в карточку пациента" as P5 #LightCyan
rectangle "6. Подготовленный диагноз, направления" as P6 #LightCyan

rectangle "1. Excel" as DS1 #LightBlue

Client --> P1 : ФИО, Жалобы
P1 --> Doctor : ФИО, Жалобы
Doctor --> P2 : Информация о приёме (ФИО, дата, услуга)
Doctor --> P3 : Данные пациента для просмотра карточки
Doctor --> P4 : Данные для анализа (результаты осмотра)
Doctor --> P5 : Обновления
Doctor --> P6 : Подготовка диагноза/рекомендаций
P2 --> DS1 : Запись в Excel (журнал приема)
P3 --> DS1 : Запись/чтение карточки (фрагменты данных)
P4 --> DS1 : Результаты анализов (для карточки)
P5 --> DS1 : Обновления записей
P5 --> DS1 : Обновление статуса/помесячная запись
P6 --> DS1 : Запись диагноза/рекомендаций
P6 --> Client : Выдача диагноза/рекомендаций
@enduml
